### ISSUE TITLE
Assigning to global 'build'

### ISSUE THREAD

**Issue by stepelu** [kikito/semver.lua#1]
Line 48: local is missing.

**Comment by stepelu** [comment]
Do you plan on releasing an updated rock spec (version 1.1.1) for this module?

**Comment by kikito** [comment]
Yes. I just wan to make sure that [travis](https://travis-ci.org/kikito/semver.lua) is green before I do that ^^

If you need the updated version right away, I suggest you just copy the semver.lua file manually into your system.

**Comment by kikito** [comment]
Hi again,

I have made some changes in semver (busted instead of telescope for the specs, markdown readme) and published a new version in luarocks.

Regards!

**Comment by stepelu** [comment]
Thanks, I noticed! :)
http://www.scilua.org/ulua_modules.html#semver

**Comment by kikito** [comment]
Cool :)
