### ISSUE TITLE
Add a copy constructor

### ISSUE THREAD

**Issue by MisterDA** [kikito/semver.lua#5]
Hi !
Could you add a copy constructor to your function `local function new(major, minor, patch, prerelease, build)` ? If I pass it a `semver` object then it returns a copy of this object.
I have a function that tests if a semver object is in a list of semvers and I want it to accept version numbers, string or a semver object and I thought this could be implemented in your library.
I think this could be easily implemented by checking if the object's metatable is the semver table but I'm not sure.

Thanks for the good work !

**Comment by kikito** [comment]
Hi,

Sorry it took me so long to answer this.

I am not going to implement this as I think the copy constructor would not be a feature useful enough for the general public. In your particular case, implementing a custom `createVersion` function which does that extra `if` and the "cloning" would be the right way to go.

Again, thanks for taking the time to write an issue on my library, and sorry that this won't be implemented.
