### ISSUE TITLE
Shouldn't the pessimistic upgrade operator return false for pre-1.0 releases?

### ISSUE THREAD

**Issue by TangentFoxy** [kikito/semver.lua#6]
According to [the spec](http://semver.org/#spec-item-4), pre-1.0 releases should be considered unstable, which means that it is not necessarily safe to upgrade between different versions.

**Comment by kikito** [comment]
You are completely right. Would you consider sending me a pull request?

**Comment by TangentFoxy** [comment]
Tried to but I'm half awake so I think it's better if I look tomorrow.

While I'm at it, should I make a new rockspec / increment patch number / etc, or leave that to you to do afterwards?? I'm also gonna give everything a look over to try to catch anything else along the way.
